name: Test that the site builds

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: google/wireit@setup-github-actions-caching/v1
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - run: npm test

      - name: Deploy Preview
        if: ${{github.event_name == 'pull_request' && !(github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]')}}
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out
          target-folder: preview/preview/preview/${{github.event.number}}
      - name: Comment about preview
        if: ${{github.event_name == 'pull_request' && !(github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]')}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview this PR: https://custom-elements-everywhere.com/preview/preview/preview/${{github.event.number}}/
